<?php
//Array
$users = array(
    'User1' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
    'User2' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
    'User3' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
    'User4' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
    'User5' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
    'User6' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
    'User7' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
    'User8' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
'User9' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
    'User10' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
    'User11' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),
    'User12' => array(
        'city'      => 'Amsterdam',
        'venue'    => 'paradeso',
        'email'     => 'some-email',
        'about'      => 'someInfo about',
    ),

);

?>